defaults: &defaults
  docker:
    - image: circleci/node:10-browsers
      environment:
        JOBS: 1
  working_directory: ~/aptoolfe

version: 2
jobs:
  checkout_code:
    <<: *defaults
    docker:
    - image: circleci/node:10-browsers
    working_directory: ~/aptoolfe
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  install_dependencies:
    <<: *defaults
    docker:
    - image: circleci/node:10-browsers
    working_directory: ~/aptoolfe
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - aptoolfe-node10-v1-{{ checksum "package-lock.json" }}
      - run: npm config set spin false
      - run:
          name: NPM Install
          command: npm install
      - save_cache:
          key: aptoolfe-node10-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/aptoolfe/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    docker:
    - image: circleci/node:10-browsers
    working_directory: ~/aptoolfe
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint Handlebars
          command: npm run lint:hbs
      - run:
          name: Lint JavaScript
          command: npm run lint:js

  test:
    <<: *defaults
    docker:
    - image: circleci/node:10-browsers
    working_directory: ~/aptoolfe
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: npm run test
    
  deploy_to_development:
    <<: *defaults
    docker:
    - image: circleci/node:10-browsers
    working_directory: ~/aptoolfe
    steps: 
      - attach_workspace:
          at: .
      - run:
          name: Push to Heroku
          command: git push https://heroku:6d93c55c-43b3-49d8-9705-b18be5bdede1@git.heroku.com/aptool.git master

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - lint:
          requires:
            - install_dependencies
      - test:
          requires:
            - install_dependencies
  build_and_deploy:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - lint:
          requires:
            - install_dependencies
      - test:
          requires:
            - install_dependencies
      - deploy_to_development:
          requires:
            - checkout_code
            - install_dependencies
            - lint
            - test
          filters:
            branches: 
              only:
                - dev

